Ranged Combat + Tile/Unit Selection Fixes
kjniemela/CivCloneJS pull request #154
Opened 2023-07-15 19:21 UTC by kjniemela

closes #115; closes #128; closes #143; closes #144; closes #147; closes #149

- Add ranged combat
- Refactor unit vision code
- Quality of life changes for how you select units and tiles on the frontend
- Improvements builders can build is now dictated by the backend, not a table on the frontend

2023-07-15 19:46 UTC, kjniemela commented
For completeness, I will at least _try_ to implement #82 in this PR.

2023-07-17 19:13 UTC, JoelNiemela requested changes

2023-07-17 20:14 UTC, kjniemela commented on src/server/game/map/tile/index.ts
> +      this.elevation + (this.improvement ? Improvement.improvementHeightTable[this.improvement.type] ?? 0 : 0)
This cannot be done in TypeScript.

2023-07-17 21:01 UTC, JoelNiemela approved these changes

2023-07-17 21:01 UTC, merged